### ISSUE TITLE
 PVR_ERROR GetTimerTypes in src/client.cpp 

### ISSUE THREAD

**Issue by kuboosoft** [kodi-pvr/pvr.demo#18]
## Hi; I use Fedora Linux 22; I try compile all pvr addons for Kodi 15; but this new Implements, breaks the build; all pvr-addons present the same problem; on may doesn't existed this issue, here the log:

~/build/BUILD/kodi-pvr-addons/pvr.demo/build ~/build/BUILD/kodi-pvr-addons
- file=addons.txt
- IFS=
- read -r line
- mkdir -p pvr.demo/build
- pushd /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/build
- cmake .. -DADDONS_TO_BUILD=pvr.demo -DADDONS_SRC_DIR=pvr-addons -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug
  -- The C compiler identification is GNU 5.1.1
  -- The CXX compiler identification is GNU 5.1.1
  -- Check for working C compiler: /usr/lib64/ccache/cc
  -- Check for working C compiler: /usr/lib64/ccache/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/lib64/ccache/c++
  -- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Checking to see if CXX compiler accepts flag -flto
  -- Checking to see if CXX compiler accepts flag -flto - yes
  -- PVRDEMO_VERSION=1.11.3
  -- Configuring done
  -- Generating done
  CMake Warning:
  Manually-specified variables were not used by the project:
    ADDONS_SRC_DIR
    ADDONS_TO_BUILD
  -- Build files have been written to: /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/build
- make
  Scanning dependencies of target pvr.demo
  [ 33%] Building CXX object CMakeFiles/pvr.demo.dir/src/client.cpp.o
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:312:25: error: 'PVR_TIMER_TYPE' was not declared in this scope
  PVR_ERROR GetTimerTypes(PVR_TIMER_TYPE types[], int _size)
                         ^
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:312:49: error: expected primary-expression before 'int'
  PVR_ERROR GetTimerTypes(PVR_TIMER_TYPE types[], int *size)
                                                 ^
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:312:58: error: expression list treated as compound expression in initializer [-fpermissive]
  PVR_ERROR GetTimerTypes(PVR_TIMER_TYPE types[], int *size)
                                                          ^
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:313:1: error: expected ',' or ';' before '{' token
  {
  ^
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp: In function 'PVR_ERROR DeleteTimer(const PVR_TIMER&, bool, bool)':
  /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:363:71: error: conflicting declaration of C function 'PVR_ERROR DeleteTimer(const PVR_TIMER&, bool, bool)'
  PVR_ERROR DeleteTimer(const PVR_TIMER &timer, bool bForceDelete, bool /_bDeleteScheduled_/) { return PVR_ERROR_NOT_IMPLEMENTED; }
                                                                       ^
  In file included from /builddir/build/BUILD/kodi-pvr-addons/pvr.demo/src/client.cpp:23:0:
  /usr/include/kodi/xbmc_pvr_dll.h:370:13: note: previous declaration 'PVR_ERROR DeleteTimer(const PVR_TIMER&, bool)'
  PVR_ERROR DeleteTimer(const PVR_TIMER& timer, bool bForceDelete);
           ^
  CMakeFiles/pvr.demo.dir/build.make:62: recipe for target 'CMakeFiles/pvr.demo.dir/src/client.cpp.o' failed
  CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/pvr.demo.dir/all' failed
  Makefile:149: recipe for target 'all' failed
  Errores de construcción RPM:
  make[2]: *_\* [CMakeFiles/pvr.demo.dir/src/client.cpp.o] Error 1
  make[1]: **\* [CMakeFiles/pvr.demo.dir/all] Error 2
  make: **\* [all] Error 2

**Comment by AlwinEsch** [comment]
Think the problem is no longer there.
